"""Instrument identifier generalization and cross-source UPI support.

Provides a unified interface for resolving and mapping instrument identifiers
across different data sources (DTCC UPI, CME contract codes, OTC CUSIPs, etc.).

This module enables:
  - Standardized instrument representation across sources
  - Bidirectional mapping between identifier types
  - Normalized querying and aggregation across multi-source data
  - Extensible resolver architecture for new identifier types
"""

from __future__ import annotations

from abc import ABC, abstractmethod
from dataclasses import dataclass, field
from enum import Enum
from typing import Dict, List, Optional, Set, Tuple
import logging

logger = logging.getLogger(__name__)


class IdentifierType(Enum):
    """Supported instrument identifier types across financial data sources."""

    # DTCC identification
    DTCC_UPI = "DTCC_UPI"
    DTCC_FISN = "DTCC_FISN"

    # CME identification
    CME_CONTRACT_CODE = "CME_CONTRACT_CODE"
    CME_PRODUCT_ID = "CME_PRODUCT_ID"

    # OTC identification
    OTC_CUSIP = "OTC_CUSIP"
    OTC_ISIN = "OTC_ISIN"

    # General identifiers
    CUSIP = "CUSIP"
    ISIN = "ISIN"
    LEI = "LEI"  # Legal Entity Identifier (counterparty)

    # Internal normalized ID (generated by resolver)
    NORMALIZED_ID = "NORMALIZED_ID"


@dataclass
class InstrumentIdentifier:
    """Represents a single instrument identifier from a specific source.

    Attributes:
        identifier_type: The type of identifier (DTCC_UPI, CME_CODE, etc.)
        identifier_value: The actual identifier string (e.g., "123ABC")
        source: The data source that provided this identifier (e.g., "DTCC", "CME")
        metadata: Optional source-specific metadata (e.g., exchange, tenor)
    """

    identifier_type: IdentifierType
    identifier_value: str
    source: str
    metadata: Dict[str, str] = field(default_factory=dict)

    def __post_init__(self):
        """Validate identifier on construction."""
        if not self.identifier_value or not self.identifier_value.strip():
            raise ValueError(f"Identifier value cannot be empty for type {self.identifier_type}")
        if not self.source or not self.source.strip():
            raise ValueError("Source cannot be empty")
        self.identifier_value = self.identifier_value.strip()
        self.source = self.source.strip()

    def __hash__(self):
        """Make hashable for use in sets and dicts."""
        return hash((self.identifier_type, self.identifier_value, self.source))

    def __eq__(self, other):
        """Equality check."""
        if not isinstance(other, InstrumentIdentifier):
            return False
        return (self.identifier_type == other.identifier_type and
                self.identifier_value == other.identifier_value and
                self.source == other.source)

    def __repr__(self) -> str:
        return f"InstrumentIdentifier({self.identifier_type.value}={self.identifier_value} from {self.source})"


@dataclass
class Instrument:
    """Represents a normalized financial instrument with multiple identifiers.

    Attributes:
        normalized_id: Internal unique identifier for this instrument across sources
        identifier_set: Set of InstrumentIdentifier objects from different sources
        name: Human-readable instrument name (e.g., "5Y Interest Rate Swap")
        instrument_type: Category (e.g., "swap", "future", "option")
        asset_class: Asset class (e.g., "interest_rate", "equity", "commodity")
        maturity_date: Optional expiration/maturity date in ISO format
        underlying: Optional underlying instrument identifier
    """

    normalized_id: str
    identifier_set: Set[InstrumentIdentifier] = field(default_factory=set)
    name: Optional[str] = None
    instrument_type: Optional[str] = None  # e.g., "swap", "future", "option"
    asset_class: Optional[str] = None  # e.g., "interest_rate", "equity"
    maturity_date: Optional[str] = None  # ISO format: YYYY-MM-DD
    underlying: Optional[str] = None
    metadata: Dict[str, str] = field(default_factory=dict)

    def add_identifier(self, identifier: InstrumentIdentifier) -> None:
        """Add an identifier mapping to this instrument."""
        self.identifier_set.add(identifier)

    def get_identifier(self, identifier_type: IdentifierType, source: Optional[str] = None) -> Optional[str]:
        """Retrieve an identifier value by type, optionally filtered by source.

        Args:
            identifier_type: The type of identifier to retrieve
            source: Optional source filter (e.g., "DTCC"). If None, returns first match.

        Returns:
            The identifier value if found, else None.
        """
        for ident in self.identifier_set:
            if ident.identifier_type == identifier_type:
                if source is None or ident.source == source:
                    return ident.identifier_value
        return None

    def get_identifiers_by_type(self, identifier_type: IdentifierType) -> List[InstrumentIdentifier]:
        """Get all identifiers of a specific type from all sources."""
        return [ident for ident in self.identifier_set if ident.identifier_type == identifier_type]

    def get_identifiers_by_source(self, source: str) -> List[InstrumentIdentifier]:
        """Get all identifiers from a specific source."""
        return [ident for ident in self.identifier_set if ident.source == source]

    def __repr__(self) -> str:
        ids_str = ", ".join(f"{i.identifier_type.value}={i.identifier_value}" for i in self.identifier_set)
        return f"Instrument({self.normalized_id}, [{ids_str}])"


class IdentifierResolver(ABC):
    """Abstract base class for instrument identifier resolution and mapping.

    Implementations map identifiers between different source types and provide
    cross-source instrument lookups.
    """

    @abstractmethod
    def resolve(self, identifier: InstrumentIdentifier) -> Optional[Instrument]:
        """Resolve a single identifier to a normalized Instrument.

        Args:
            identifier: The InstrumentIdentifier to resolve

        Returns:
            An Instrument with potentially multiple identifier mappings,
            or None if resolution failed.
        """
        pass

    @abstractmethod
    def resolve_by_id(self, identifier_value: str, identifier_type: IdentifierType,
                      source: Optional[str] = None) -> Optional[Instrument]:
        """Convenience method: resolve by value and type instead of creating an object.

        Args:
            identifier_value: The identifier string (e.g., "123ABC")
            identifier_type: The type of identifier
            source: Optional source hint (e.g., "DTCC")

        Returns:
            An Instrument if resolution succeeded, else None.
        """
        pass

    @abstractmethod
    def map_identifier(self, source_identifier: InstrumentIdentifier,
                      target_type: IdentifierType) -> Optional[str]:
        """Map one identifier type to another (e.g., DTCC UPI -> CME Code).

        Args:
            source_identifier: The identifier to map
            target_type: The desired identifier type

        Returns:
            The target identifier value if a mapping exists, else None.
        """
        pass

    @abstractmethod
    def get_all_identifiers(self, instrument: Instrument) -> Dict[IdentifierType, List[str]]:
        """Retrieve all known identifiers for an instrument, grouped by type.

        Args:
            instrument: The Instrument to look up

        Returns:
            Dict mapping IdentifierType to list of values
        """
        pass


class LocalIdentifierResolver(IdentifierResolver):
    """Reference implementation: in-memory identifier mapping resolver.

    Uses a simple dict-based mapping store. For production use with large
    identifier datasets, implement a resolver backed by a database or
    remote service (RemoteIdentifierResolver, DatabaseIdentifierResolver).
    """

    def __init__(self):
        """Initialize the resolver with an empty mapping store."""
        # Map: normalized_id -> Instrument
        self._instruments: Dict[str, Instrument] = {}

        # Map: (identifier_value, identifier_type, source) -> normalized_id
        self._identifier_to_normalized: Dict[Tuple[str, IdentifierType, str], str] = {}

        # Map: (source_id, target_type) -> target_id (for cross-source mapping)
        self._cross_source_mappings: Dict[Tuple[str, IdentifierType], Set[str]] = {}

    def resolve(self, identifier: InstrumentIdentifier) -> Optional[Instrument]:
        """Resolve an identifier to a normalized Instrument."""
        key = (identifier.identifier_value, identifier.identifier_type, identifier.source)
        normalized_id = self._identifier_to_normalized.get(key)

        if normalized_id:
            return self._instruments.get(normalized_id)

        # No existing mapping; create new Instrument
        normalized_id = self._generate_normalized_id(identifier)
        instrument = Instrument(normalized_id=normalized_id)
        instrument.add_identifier(identifier)

        self._instruments[normalized_id] = instrument
        self._identifier_to_normalized[key] = normalized_id

        return instrument

    def resolve_by_id(self, identifier_value: str, identifier_type: IdentifierType,
                      source: Optional[str] = None) -> Optional[Instrument]:
        """Convenience method for resolve()."""
        if source is None:
            # Try to find any match; return first
            for (val, itype, src), norm_id in self._identifier_to_normalized.items():
                if val == identifier_value and itype == identifier_type:
                    return self._instruments.get(norm_id)
            return None

        identifier = InstrumentIdentifier(identifier_type, identifier_value, source)
        return self.resolve(identifier)

    def map_identifier(self, source_identifier: InstrumentIdentifier,
                      target_type: IdentifierType) -> Optional[str]:
        """Map one identifier type to another via normalized Instrument."""
        instrument = self.resolve(source_identifier)
        if instrument:
            return instrument.get_identifier(target_type)
        return None

    def get_all_identifiers(self, instrument: Instrument) -> Dict[IdentifierType, List[str]]:
        """Retrieve all identifiers for an instrument grouped by type."""
        result: Dict[IdentifierType, List[str]] = {}
        for identifier in instrument.identifier_set:
            if identifier.identifier_type not in result:
                result[identifier.identifier_type] = []
            result[identifier.identifier_type].append(identifier.identifier_value)
        return result

    def add_mapping(self, instrument_id: str, identifier: InstrumentIdentifier) -> None:
        """Manually add an identifier to an existing Instrument.

        Args:
            instrument_id: The normalized Instrument ID
            identifier: The InstrumentIdentifier to add
        """
        if instrument_id in self._instruments:
            instrument = self._instruments[instrument_id]
            instrument.add_identifier(identifier)
            key = (identifier.identifier_value, identifier.identifier_type, identifier.source)
            self._identifier_to_normalized[key] = instrument_id

    def _generate_normalized_id(self, identifier: InstrumentIdentifier) -> str:
        """Generate a normalized ID from an identifier.

        For the reference implementation, use source + value.
        Production resolvers should use deterministic hashing or database sequences.
        """
        return f"{identifier.source}_{identifier.identifier_type.value}_{identifier.identifier_value}"

    def merge_instruments(self, primary_id: str, secondary_id: str) -> None:
        """Merge two Instruments, consolidating their identifier sets.

        All identifiers from secondary_id move to primary_id; secondary_id is deleted.

        Args:
            primary_id: The Instrument ID to keep
            secondary_id: The Instrument ID to merge into primary
        """
        if primary_id not in self._instruments or secondary_id not in self._instruments:
            raise ValueError("One or both instrument IDs do not exist")

        primary = self._instruments[primary_id]
        secondary = self._instruments[secondary_id]

        # Move all identifiers from secondary to primary
        for identifier in secondary.identifier_set:
            primary.add_identifier(identifier)
            key = (identifier.identifier_value, identifier.identifier_type, identifier.source)
            self._identifier_to_normalized[key] = primary_id

        # Update metadata if secondary has richer data
        if secondary.name and not primary.name:
            primary.name = secondary.name
        if secondary.instrument_type and not primary.instrument_type:
            primary.instrument_type = secondary.instrument_type
        if secondary.asset_class and not primary.asset_class:
            primary.asset_class = secondary.asset_class

        # Delete secondary
        del self._instruments[secondary_id]

        logger.info(f"Merged instrument {secondary_id} into {primary_id}")


class IdentifierResolverFactory:
    """Factory for creating and retrieving IdentifierResolver instances.

    Supports registration of custom resolver implementations and provides
    access to configured resolvers by name.
    """

    _resolvers: Dict[str, IdentifierResolver] = {}
    _resolver_classes: Dict[str, type] = {}

    @classmethod
    def register_resolver(cls, name: str, resolver: IdentifierResolver) -> None:
        """Register a resolver instance by name."""
        cls._resolvers[name] = resolver
        logger.info(f"Registered resolver: {name}")

    @classmethod
    def register_resolver_class(cls, name: str, resolver_class: type) -> None:
        """Register a resolver class for lazy instantiation."""
        cls._resolver_classes[name] = resolver_class

    @classmethod
    def get_resolver(cls, name: str) -> Optional[IdentifierResolver]:
        """Get a resolver by name, instantiating if needed."""
        if name in cls._resolvers:
            return cls._resolvers[name]

        if name in cls._resolver_classes:
            resolver = cls._resolver_classes[name]()
            cls._resolvers[name] = resolver
            return resolver

        return None

    @classmethod
    def list_resolvers(cls) -> List[str]:
        """List names of registered resolvers."""
        return list(set(cls._resolvers.keys()) | set(cls._resolver_classes.keys()))


# Initialize the default local resolver
_default_resolver = LocalIdentifierResolver()
IdentifierResolverFactory.register_resolver("default", _default_resolver)
IdentifierResolverFactory.register_resolver("local", _default_resolver)
